services:
  mealie:
    container_name: app-mealie
    image: hkotel/mealie:v3.14.0@sha256:6785e5ca87f0ae25f90be850fd1473e92a2c0bde1b5ef07be111c4c9565aeb75
    volumes:
      - ./mealie-data:/app/data/
    ports:
      - 9091:9000
    environment:
      TZ: Europe/Paris
    restart: unless-stopped
    
volumes:
  mealie-data:
   