version: '3.8'

services:
  memos:
    image: neosmemo/memos:0.26.1@sha256:7bf4a85c67fa7d579513c0308f5cd637537076e0937b6b98876d3b5c4d7f1990
    container_name: app-memos
    ports:
      - "3016:5230"
    volumes:
      - ./memos:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_ADDR=0.0.0.0
      - MEMOS_PORT=5230
      - MEMOS_DATA=/var/opt/memos
    restart: unless-stopped
